### ISSUE TITLE
Enhancement: Allow API query param to specify a timeout when trying to reach the server.

### ISSUE THREAD

**Issue by eclair4151** [mcstatus-io/ping-server#8]
Hello! I’ve got a kind of simple feature request. Not sure how easy it would be to throw in at some point :)

From my testing, it seems if a server is offline, this API will wait 10 seconds or so before giving up and returning an offline status. 
For my use case, I know if it doesn't respond within 5, it won't be online. 
It would be nice to keep the default behavior, but add a query param like 

?serverQueryTimeout=5

which would let you override it to a shorter period.
Thanks!

**Comment by PassTheMayo** [comment]
This is something that would be relatively simple for me to implement. I'll go ahead and get started right now, and I'll let you know when the changes are live.

**Comment by PassTheMayo** [comment]
This actually turned out to be a much larger endeavour than I previously expected. I had to almost completely rewrite the status retrieval library to better support timeouts, but the changes are live on the official API right now. You can use `?timeout=<value>` to specify how long until the status/query retrieval times out. During this time, if the server retrieves the status of a server but not the query, it will only wait for 500 milliseconds until returning a response without any query information. Thank you for your enchancement.

**Comment by eclair4151** [comment]
Oh wow, thank you very much for the fast response, very much appreciated!
